# fly.toml app configuration file generated for pss on 2023-11-18T00:26:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pss"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
